package io.rueishi.marketdata.crypto.venue.coinbase.l2;

import io.rueishi.marketdata.crypto.core.config.InstrumentConfig;
import io.rueishi.marketdata.crypto.core.subscription.SubscriptionBuilder;
import io.rueishi.marketdata.crypto.venue.coinbase.shared.CoinbaseAuthenticator;
import io.rueishi.marketdata.crypto.venue.coinbase.shared.CoinbaseConfig;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.agrona.concurrent.EpochClock;
import org.agrona.concurrent.SystemEpochClock;

/**
 * Coinbase L2 authenticated WebSocket subscription payload builder.
 *
 * <p>{@code CoinbaseL2SubscriptionBuilder} is the venue-specific implementation
 * of the shared {@link SubscriptionBuilder} contract for the Coinbase Exchange
 * Direct Feed {@code level2} strategy. Connector factory code creates one
 * builder from typed {@link CoinbaseConfig} and a {@link CoinbaseAuthenticator},
 * then {@code AbstractConnector} calls {@link #buildSubscribe(InstrumentConfig)}
 * after connection establishment and {@link #buildUnsubscribe(InstrumentConfig)}
 * during shutdown or recovery control flow.</p>
 *
 * <p>The builder emits one UTF-8 JSON text-frame payload per method call. Each
 * payload contains the configured instrument product id, both required Phase 2
 * channels ({@code level2} and {@code heartbeat}), and Coinbase authentication
 * fields generated by the shared authenticator. Payload field order is stable
 * so tests can verify exact output, but parsers must still treat JSON field
 * order as irrelevant.</p>
 */
public final class CoinbaseL2SubscriptionBuilder implements SubscriptionBuilder {
    /** Coinbase L2 book channel required by Phase 2. */
    public static final String LEVEL2_CHANNEL = "level2";
    /** Coinbase heartbeat channel required by Phase 2 liveness handling. */
    public static final String HEARTBEAT_CHANNEL = "heartbeat";

    private final CoinbaseAuthenticator authenticator;
    private final EpochClock epochClock;
    private final List<String> channels;

    /**
     * Creates a builder with the system epoch clock.
     *
     * <p>Production connector factories can use this constructor when they do
     * not need to override timestamp generation. Tests generally use the
     * explicit clock constructor for deterministic payloads.</p>
     *
     * @param config typed Coinbase venue config
     * @throws NullPointerException if {@code config} is null
     * @throws IllegalArgumentException if credentials or required channels are invalid
     */
    public CoinbaseL2SubscriptionBuilder(CoinbaseConfig config) {
        this(config, new CoinbaseAuthenticator(config), SystemEpochClock.INSTANCE);
    }

    /**
     * Creates a builder with explicit authentication and clock dependencies.
     *
     * <p>This constructor is used by tests and later connector factories that
     * already constructed a shared authenticator. It validates that the
     * configured channel list includes both {@code level2} and {@code heartbeat}
     * before any network send can occur.</p>
     *
     * @param config typed Coinbase venue config containing channel selection
     * @param authenticator shared Coinbase authentication helper
     * @param epochClock injectable clock used for auth timestamp generation
     * @throws NullPointerException if any dependency is null
     * @throws IllegalArgumentException if the channel list omits a required channel
     */
    public CoinbaseL2SubscriptionBuilder(
            CoinbaseConfig config,
            CoinbaseAuthenticator authenticator,
            EpochClock epochClock) {
        Objects.requireNonNull(config, "config");
        this.authenticator = Objects.requireNonNull(authenticator, "authenticator");
        this.epochClock = Objects.requireNonNull(epochClock, "epochClock");
        this.channels = requiredChannels(config.channels());
    }

    /**
     * Builds one authenticated Coinbase subscribe JSON payload.
     *
     * <p>The payload is intended for the WebSocket text-frame path immediately
     * after connection establishment. It contains the instrument's
     * {@code exchangeSymbol}, the configured channel list, and fresh auth fields
     * for the current epoch second.</p>
     *
     * @param instrument configured instrument to subscribe
     * @return UTF-8 encoded Coinbase subscribe JSON payload
     * @throws NullPointerException if {@code instrument} is null
     * @throws IllegalArgumentException if {@code instrument.exchangeSymbol} is blank
     */
    @Override
    public byte[] buildSubscribe(InstrumentConfig instrument) {
        return buildPayload("subscribe", instrument);
    }

    /**
     * Builds one authenticated Coinbase unsubscribe JSON payload.
     *
     * <p>The unsubscribe mirrors the subscribe control-plane scope: the same
     * product id and channels are used with {@code "type":"unsubscribe"} so
     * shutdown and recovery can remove exactly the subscription this builder
     * created.</p>
     *
     * @param instrument configured instrument to unsubscribe
     * @return UTF-8 encoded Coinbase unsubscribe JSON payload
     * @throws NullPointerException if {@code instrument} is null
     * @throws IllegalArgumentException if {@code instrument.exchangeSymbol} is blank
     */
    @Override
    public byte[] buildUnsubscribe(InstrumentConfig instrument) {
        return buildPayload("unsubscribe", instrument);
    }

    /**
     * Serializes a Coinbase control-plane payload with stable field order.
     *
     * @param type Coinbase control-plane type, either subscribe or unsubscribe
     * @param instrument configured instrument whose exchange symbol becomes product id
     * @return UTF-8 JSON payload bytes
     */
    private byte[] buildPayload(String type, InstrumentConfig instrument) {
        Objects.requireNonNull(instrument, "instrument");
        String productId = requireText(instrument.exchangeSymbol, "instrument.exchangeSymbol");
        CoinbaseAuthenticator.AuthFields authFields = authenticator.authFields(epochClock);

        StringBuilder builder = new StringBuilder(256);
        builder.append('{');
        appendField(builder, "type", type).append(',');
        appendArrayField(builder, "product_ids", List.of(productId)).append(',');
        appendArrayField(builder, "channels", channels).append(',');
        appendField(builder, "signature", authFields.signature()).append(',');
        appendField(builder, "key", authFields.key()).append(',');
        appendField(builder, "passphrase", authFields.passphrase()).append(',');
        appendField(builder, "timestamp", authFields.timestamp());
        builder.append('}');
        return builder.toString().getBytes(StandardCharsets.UTF_8);
    }

    private static List<String> requiredChannels(List<String> configuredChannels) {
        Objects.requireNonNull(configuredChannels, "configuredChannels");
        List<String> result = new ArrayList<>(configuredChannels.size());
        for (String channel : configuredChannels) {
            String text = requireText(channel, "channel");
            if (!result.contains(text)) {
                result.add(text);
            }
        }
        if (!result.contains(LEVEL2_CHANNEL) || !result.contains(HEARTBEAT_CHANNEL)) {
            throw new IllegalArgumentException("Coinbase L2 subscriptions require level2 and heartbeat channels");
        }
        return List.copyOf(result);
    }

    private static StringBuilder appendField(StringBuilder builder, String name, String value) {
        return builder.append('"')
                .append(name)
                .append("\":\"")
                .append(escapeJson(value))
                .append('"');
    }

    private static StringBuilder appendArrayField(StringBuilder builder, String name, List<String> values) {
        builder.append('"').append(name).append("\":[");
        for (int i = 0; i < values.size(); i++) {
            if (i > 0) {
                builder.append(',');
            }
            builder.append('"').append(escapeJson(values.get(i))).append('"');
        }
        return builder.append(']');
    }

    private static String escapeJson(String value) {
        StringBuilder escaped = null;
        for (int i = 0; i < value.length(); i++) {
            char current = value.charAt(i);
            String replacement = switch (current) {
                case '"' -> "\\\"";
                case '\\' -> "\\\\";
                case '\b' -> "\\b";
                case '\f' -> "\\f";
                case '\n' -> "\\n";
                case '\r' -> "\\r";
                case '\t' -> "\\t";
                default -> current < 0x20 ? unicodeEscape(current) : null;
            };
            if (replacement != null) {
                if (escaped == null) {
                    escaped = new StringBuilder(value.length() + 8);
                    escaped.append(value, 0, i);
                }
                escaped.append(replacement);
            } else if (escaped != null) {
                escaped.append(current);
            }
        }
        return escaped == null ? value : escaped.toString();
    }

    private static String requireText(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " is required");
        }
        return value;
    }

    private static String unicodeEscape(char value) {
        char[] escaped = {'\\', 'u', '0', '0', '0', '0'};
        int code = value;
        for (int i = 5; i >= 2; i--) {
            int nibble = code & 0xF;
            escaped[i] = (char) (nibble < 10 ? '0' + nibble : 'a' + (nibble - 10));
            code >>>= 4;
        }
        return new String(escaped);
    }
}
