plugins {
    id 'java'
}

group = 'io.rueishi.marketdata'
version = '0.0.1-SNAPSHOT'
description = 'Low-latency crypto market data gateway.'

layout.buildDirectory = layout.projectDirectory.dir('build-gradle')

ext {
    agronaVersion = '1.20.0'
    archUnitVersion = '1.2.1'
    assertjVersion = '3.24.2'
    byteBuddyAgentVersion = '1.14.9'
    hdrHistogramVersion = '2.1.12'
    junitJupiterVersion = '5.10.0'
    log4j2Version = '2.25.2'
    lmaxDisruptorVersion = '4.0.0'
    nettyVersion = '4.1.100.Final'
    nettyTcnativeVersion = '2.0.61.Final'
    snakeYamlVersion = '2.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

dependencies {
    implementation "io.netty:netty-all:${nettyVersion}"
    implementation "io.netty:netty-transport-native-epoll:${nettyVersion}"
    implementation "io.netty:netty-tcnative-boringssl-static:${nettyTcnativeVersion}"

    implementation "org.agrona:agrona:${agronaVersion}"

    implementation "org.yaml:snakeyaml:${snakeYamlVersion}"
    compileOnly "org.hdrhistogram:HdrHistogram:${hdrHistogramVersion}"

    implementation "org.apache.logging.log4j:log4j-api:${log4j2Version}"
    implementation "org.apache.logging.log4j:log4j-core:${log4j2Version}"
    implementation "com.lmax:disruptor:${lmaxDisruptorVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitJupiterVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "com.tngtech.archunit:archunit-junit5:${archUnitVersion}"
    testImplementation "net.bytebuddy:byte-buddy-agent:${byteBuddyAgentVersion}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.9'
}

test {
    useJUnitPlatform()
}
